### ISSUE TITLE
Somethings Wrong

### ISSUE THREAD

**Issue by ghost** [LEAFERx/hexo-leancloud-counter-security#2]
When I use this plug-in, the hexo prompts an error.
Here is the error picture.
![default](https://user-images.githubusercontent.com/17929366/36347941-d33c2bec-145c-11e8-80f1-0c1493e873b6.PNG)
Please ignore Chinese.

**Comment by LEAFERx** [comment]
leancloud_counter_security是在博客站点配置文件里配置的 不是主题配置文件

**Comment by LEAFERx** [comment]
https://leaferx.online/2018/02/11/lc-security/

**Comment by LEAFERx** [comment]
看这里的详细说明

**Comment by ghost** [comment]
是要先配置再敲命令行还是先敲命令行在配置

**Comment by LEAFERx** [comment]
先配置

**Comment by ghost** [comment]
OK，原文章貌似表达不太恰当，你写的先敲命令行再配置。望在这一步能强调下。

**Comment by LEAFERx** [comment]
抱歉 我没有注意 会尽快修复

**Comment by ghost** [comment]
@LEAFERx 最后一步我deploy时又出现问题了,这个type不懂放哪里，我放着放出问题了
我的配置：
```yml
deploy:
  type: git
  repository: git@git.coding.net:wuhang2003/wuhang2003.coding.me.git
  branch: master
  
  - type: leancloud_counter_security_sync
```
问题截图：
![default](https://user-images.githubusercontent.com/17929366/36350688-55f3268a-1494-11e8-9f08-e374c3687bf8.PNG)
烦请大佬贴一下自己的配置文件

**Comment by LEAFERx** [comment]
```yml
deploy:
- type: git
  repo: https://github.com/LEAFERx/leaferx.github.io.git
- type: baidu_url_submitter
- type: leancloud_counter_security_sync
```

yml中列表的写法是前面加`-`
